import {
  Rocket,
  Zap,
  Shapes,
  Layers,
  Wand2,
  Sparkles,
  Play,
  Brain,
  Bot,
  Sun,
  Leaf,
  Target,
  HeartPulse,
  Timer,
  NotebookPen,
  Dumbbell,
  Compass,
  Image as ImageIcon,
  Battery,
} from 'lucide-react'

// Curated set of icons available for apps
export const altIconChoices = [
  { key: 'rocket', Cmp: Rocket },
  { key: 'zap', Cmp: Zap },
  { key: 'shapes', Cmp: Shapes },
  { key: 'layers', Cmp: Layers },
  { key: 'wand2', Cmp: Wand2 },
  { key: 'sparkles', Cmp: Sparkles },
  { key: 'play', Cmp: Play },
  { key: 'brain', Cmp: Brain },
  { key: 'bot', Cmp: Bot },
  { key: 'sun', Cmp: Sun },
  { key: 'leaf', Cmp: Leaf },
  { key: 'target', Cmp: Target },
  { key: 'heartpulse', Cmp: HeartPulse },
  { key: 'timer', Cmp: Timer },
  { key: 'notebook', Cmp: NotebookPen },
  { key: 'dumbbell', Cmp: Dumbbell },
  { key: 'compass', Cmp: Compass },
  { key: 'image', Cmp: ImageIcon },
  { key: 'battery', Cmp: Battery },
]

